### ISSUE TITLE
Api for customizing the widget

### ISSUE THREAD

**Issue by Adevien** [kokemus/barcode_scanner#1]
Hi, is there a way to handle the widget's / video size? i've been looking forward to build it for myself but it has errors on build.

**Comment by kokemus** [comment]
There is now the option to define video size.

```
BarcodeScanner scanner = await BarcodeScannerFactory.create(
  BarcodeScannerOptions(formats: ['ean_13', 'qr_code']),
  VideoConstraints(width: 600, height: 200)
);
```
